image: php

variables:
  DOCKER_DRIVER: overlay2
  REGISTRY: registry.gitlab.com
  REGISTRY_USER: gitlab-ci-token
  REGISTRY_PASSWORD: $CI_JOB_TOKEN
  REPOSITORY_PATH: developersforfuture/registry
  CONTAINER_IMAGE: ${REGISTRY}/${REPOSITORY_PATH}/app
  COMPOSE_PROJECT_NAME: developers
  VERSION_TAG: ${CI_COMMIT_REF_NAME}

stages:
  -  build-ci
  - test
  - release
  - deploy

.cache_template:
  cache: &cache_definition
    key: "$CI_PROJECT_ID"
    paths:
      - vendor
      - web/build
      - node_modules
      - $HOME/.composer
.build_service_template: &build_service
  cache: *cache_definition
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3 curl git make m4
    - curl -L -o /usr/local/bin/dobi "https://github.com/dnephin/dobi/releases/download/v0.12.0/dobi-$(uname -s)"; chmod +x /usr/local/bin/dobi
    - make docker_login
  script:
    - if [[ "${RUNTIME"} === "productio" ]]; then export VERSION_TAG=${CI_COMMIT_TAG};  fi;
    - make build
    - make push
  after_script:
    - make docker_logout

build-image.ci:
  <<: *build_service
  stage:  build-ci
  except: [tags]
  variables:
    RUNTIME: 'ci'

test_unit:
  cache: *cache_definition
  image: ${CONTAINER_IMAGE}-ci:${VERSION_TAG}
  stage: test
  except: [tags]
  variables:
    DB_ROOT_PW: root
    DB_DATABASE: developers
    DB_HOST: mysql
    DB_USER: developers
    DB_PASSWORD: developers
    APP_DEBUG: 0
    APP_ENV: test
    SYMFONY_ENV: test
  script:
    - vendor/bin/phpunit
  artifacts:
    name: "${CI_JOB_NAME}_${CI_JOB_ID}"
    expire_in: 1 week
    when: always
    paths:
      - ./coverage/
      - ./unittests.xml
    reports:
      junit: ./unittests.xml
  coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'

build-image.production:
  <<: *build_service
  stage: release
  only: [tags]
  variables:
    RUNTIME: 'production'

build-image.development:
  <<: *build_service
  stage: release
  when: manual
  variables:
    RUNTIME: 'development'

build-image.staging:
  <<: *build_service
  stage: release
  only: [branches]
  except: [tags]
  variables:
    RUNTIME: 'staging'
    CONTEXT_PATH: './'

.deploy_template: &deploy_job
  stage: deploy
  script:
    - echo " + + + We would deplyo ${RUNTIME} now + + + "

deploy-as-branch.staging:
  <<: *deploy_job
  only: ["branches"]
  except: ["master"]
  variables:
    RUNTIME: staging
    COMPOSE_PROJECT_NAME: ${CI_PROJECT_ID}-${RUNTIME}
  environment:
    name: runtime/${RUNTIME}
    url: https://staging.developersforfuture.org

deploy-as-master.staging:
  <<: *deploy_job
  only: [master]
  except: [tags]
  when: manual
  variables:
    RUNTIME: staging
    COMPOSE_PROJECT_NAME: ${CI_PROJECT_ID}-${RUNTIME}
  environment:
    name: runtime/${RUNTIME}
    url: https://staging.developersforfuture.org

deploy.production:
  <<: *deploy_job
  only: [tags]
  variables:
    RUNTIME: production
    COMPOSE_PROJECT_NAME: ${CI_PROJECT_ID}-${RUNTIME}
  environment:
    name: runtime/${RUNTIME}
    url: https://developersforfuture.org
