home_redirect:
  path: /
  defaults:
    _controller: lunetics_locale.switcher_controller:switchAction
    route: '/cms/routes/%locale%/home'
    statusCode: 301
    useReferrer: false

home_locale_redirect:
  path: /
  defaults:
    _controller: lunetics_locale.switcher_controller:switchAction
    route: '/cms/routes/%locale%/home'
    statusCode: 301
    useReferrer: false
    prefix:   /{_locale}
