swiftmailer:
    url: '%env(MAILER_URL)%'
    sender_address: 'verify@econ4future.org'
    port: 587
    logging: ~
    encryption: tls
    auth_mode: login
    stream-options:
        ssl:
            allow_self_signed: true
            verify_peer: false
    timeout: 30
