home_redirect:
    path: /
    defaults:
        _controller: lunetics_locale.switcher_controller:switchAction
        route: 'home'
        statusCode: 301
        useReferrer: false

home:
    path: /%locale%/home
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: "pages/home.html.twig"
