App\Document\StaticPage:
    definitions:
        - { uri_schema: '/{title}' }
    token_providers:
        title: [content_method, {method: getName }]
App\Document\BlogPage:
    definitions:
        - { uri_schema: '/blog/{name}' }
    token_providers:
        name: [content_method, {method: getName }]
