apiVersion: v1
kind: Service
metadata:
  namespace: froscon
  name: froscon-web
  labels:
    app.kubernetes.io/name: froscon-web
    app.kubernetes.io/instance: froscon-web-v1
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: froscon
    app.kubernetes.io/managed-by: max
spec:
  ports:
    -
      name: "http"
      port: 6092
      targetPort: 80
      protocol: "TCP"
  selector:
    app.kubernetes.io/name: froscon-web
    app.kubernetes.io/instance: froscon-web-v1
    app.kubernetes.io/version: "v1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: froscon
  name: froscon-web-v1
  labels:
    app.kubernetes.io/name: froscon-web
    app.kubernetes.io/instance: froscon-web-v1
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: froscon
    app.kubernetes.io/managed-by: max
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: froscon-web
      app.kubernetes.io/instance: froscon-web-v1
      app.kubernetes.io/version: "v1"
  replicas: 2
  template:
    metadata:
      name: froscon-web-v1
      labels:
        app.kubernetes.io/name: froscon-web
        app.kubernetes.io/instance: froscon-web-v1
        app.kubernetes.io/version: "v1"
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - env:
            - name: APP_BASEDIR_LOG
              value: /app/log
            - name: APP_BASEDIR_SRC
              value: /app/src
            - name: APP_BASEDIR_TMP
              value: /app/tmp
            - name: APP_DEBUG
              value: "0"
            - name: APP_ENV
              value: "prod"
            - name: APP_GROUP_ID
              value: "1000"
            - name: APP_PHP_MODULE_DIRECTORY
              value: /etc/php7/conf.d
            - name: APP_USER_ID
              value: "1000"
            - name: APP_WEBROOT
              value: /app/src/public
            - name: BASE_URL
              value: froscon.local.k8s
            - name: COMPOSER_CACHE_DIR
              value: /build/cache/composeer
            - name: CONTAINER_DEBUG
              value: "0"
            - name: DB_DATABASE
              value: froscon
            - name: DB_HOST
              value: froscon-mysql
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: froscon-db
            - name: DB_ROOT_PW
              valueFrom:
                secretKeyRef:
                  key: root
                  name: froscon-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: froscon-db
            - name: DB_URL
              value: mysql://${DB_USER}:${DB_PASSWORD}@froscon-mysql:3306/froscon
            - name: PHPCR_PASSWORD
              value: admin
            - name: PHPCR_USER
              value: admin
            - name: PHPCR_WORKSPACE
              value: froscon
            - name: RUNTIME
              value: development
            - name: SYMFONY_ENV
              value: dev
            - name: SYSTEM_APPUSER_NAME
              value: appuser9
            - name: VERSION_TAG
            - name: XDEBUG_ENABLED
              value: "1"
          image: registry.gitlab.com/froscon/php-track-web/app-production:0.2.16
          name: froscon-web
          ports:
            - containerPort: 80
              name: "http"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "248Mi"
              cpu: "300m"
