# Read the documentation: https://symfony.com/doc/master/cmf/bundles/seo/configuration.html
cmf_seo:
    persistence:
        phpcr: ~
    title: '%%content_title%% | %default_title%'
    description: '%%content_description%% %default_description%'



sonata_seo:
    page:
        title: Developers For Future
        metas:
            name:
                "viewport": " minimum-scale=1.0, maximum-scale=1.0, width=device-width, user-scalable=no"
                keywords: 'web, development, infrastructure, climate'
                title: '%default_title%'
                description: '%default_description%'
                "msapplication-TileColor": "#ffffff"
                "msapplication-TileImage": "%base_url%/favicons/ms-icon-144x144.png"
                "theme-color": "#ffffff"
                "referrer": "origin"
                "twitter:site": "%default_title%"
                "twitter:creator": "@DevelopersForFuture"
                "twitter:card": "summary_large_image"
                "twitter:title": '%default_title%'
                "twitter:description": '%default_description%'
                "twitter:url": "%base_url%"
                "twitter:image": "%base_url%/img/twitter_card.jpeg"
            http-equiv:
                "Content-Type": "text/html; charset=utf-8"
            property:
                "og:locale": "de-DE"
                "og:site_name": '%default_title%'
                "og:type": "article"
                "og:title": '%default_title%'
                "og:description": '%default_description%'
                "og:url": "%base_url%"
                "og:image": "%default_page_image%"
                "og:image:alt": "%default_description%"
                "article:author": "%base_url%"
                "article:publisher": "%base_url%"
